export const DeliveryStatus = {
    SHIPPED: 'SHIPPED',
    IN_TRANSIT:'IN_TRANSIT',
    PICKED_UP:'PICKED_UP',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERY_FAILED:'DELIVERY_FAILED',
    DELAYED:'DELAYED',
    DELIVERED: 'DELIVERED',
    CANCELED: 'CANCELED',
    RETURNED: 'RETURNED',
};