export const OrderStatus={
    PENDING:'PENDING',
    CONFIRMED:'CONFIRMED',
    PROCESSING:'PROCESSING',
    SHIPPED:'SHIPPED',
    DELIVERED:'DELIVERED',
    CANCELLED:'CANCELLED',
    RETURNED:'RETURNED',
    REFUNDED:'REFUNDED',
    FAILED:'FAILED'
}