export const PaymentMethod = {
    CREDIT_CARD: 'CREDIT_CARD',
    DEBIT_CARD: 'DEBIT_CARD',
    NET_BANKING: 'NET_BANKING',
    UPI: 'UPI',
    GOOGLE_PAY: 'GOOGLE_PAY',
    STRIPE:'STRIPE',
    PAYPAL:'PAYPAL',
    RAZORPAY:'RAZORPAY',
    AMAZON_PAY: 'AMAZON_PAY',
    CASH_ON_DELIVERY: 'CASH_ON_DELIVERY',
    GIFT_CARD: 'GIFT_CARD'
};


export const PaymentStatus={
    PENDING:'PENDING',
    COMPLETED:'COMPLETED',
    FAILED:'FAILED',
    REFUNDED:'REFUNDED'
}
